// Do not edit this file as it is an auto generated file
// If you need to update this file, please look into "/scripts/generate-component-mapper.ts"

import { BlogDetail } from '../components/authorable/BlogDetail';
import { BlogList } from '../components/authorable/BlogList';
import { BoxCards } from '../components/authorable/BoxCards';
import { Coaches } from '../components/authorable/Coaches';
import { ContentRte } from '../components/authorable/ContentRte';
import { ContentRteComponent } from '../components/authorable/ContentRteComponent';
import { EventsCard } from '../components/authorable/EventsCard';
import { EventsList } from '../components/authorable/EventsList';
import { Faq } from '../components/authorable/Faq';
import { FaqComponent } from '../components/authorable/FaqComponent';
import { Footer } from '../components/authorable/Footer';
import { FormWrapper } from '../components/authorable/FormWrapper';
import { GamesBoxCard } from '../components/authorable/GamesBoxCard';
import { GamesBoxCardsList } from '../components/authorable/GamesBoxCardsList';
import { Header } from '../components/authorable/Header';
import { HeroBannerComponent } from '../components/authorable/HeroBannerComponent';
import { HorizontalDivider } from '../components/authorable/HorizontalDivider';
import { Iconlist } from '../components/authorable/Iconlist';
import { InlineBanner } from '../components/authorable/InlineBanner';
import { InlineBannerComponent } from '../components/authorable/InlineBannerComponent';
import { Job } from '../components/authorable/Job';
import { JobList } from '../components/authorable/JobList';
import { Layout } from '../components/authorable/Layout';
import { LocationBookingBannerComponent } from '../components/authorable/LocationBookingBannerComponent';
import { Locations } from '../components/authorable/Locations';
import { MembershipContent } from '../components/authorable/MembershipContent';
import { MembershipContentComponent } from '../components/authorable/MembershipContentComponent';
import { PromoCardsList } from '../components/authorable/PromoCardsList';
import { PromoTwocolCards } from '../components/authorable/PromoTwocolCards';
import { QuickCardNavigation } from '../components/authorable/QuickCardNavigation';
import { RteStripComponent } from '../components/authorable/RteStripComponent';
import { Section } from '../components/authorable/Section';
import { SingleRteStrip } from '../components/authorable/SingleRteStrip';
import { SingleTestimonial } from '../components/authorable/SingleTestimonial';
import { SliderComponent } from '../components/authorable/SliderComponent';
import { StatsSectionComponent } from '../components/authorable/StatsSectionComponent';
import { UpcomingSessionCardList } from '../components/authorable/UpcomingSessionCardList';
import { VideoBanner } from '../components/authorable/VideoBanner';
import { VideoComponent } from '../components/authorable/VideoComponent';
import { ComingSoon } from '../components/authorable/location-page-components/ComingSoon';
import { ContactInformation } from '../components/authorable/location-page-components/ContactInformation';
import { CustomClubFitting } from '../components/authorable/location-page-components/CustomClubFitting';
import { DuckpinBowling } from '../components/authorable/location-page-components/DuckpinBowling';
import { DuckpinBowlingSection } from '../components/authorable/location-page-components/DuckpinBowlingSection';
import { FreeParking } from '../components/authorable/location-page-components/FreeParking';
import { GolfInstruction } from '../components/authorable/location-page-components/GolfInstruction';
import { LocationDropdown } from '../components/authorable/location-page-components/LocationDropdown';
import { LocationHeroBanner } from '../components/authorable/location-page-components/LocationHeroBanner';
import { MakeItAParty } from '../components/authorable/location-page-components/MakeItAParty';
import { MembershipSection } from '../components/authorable/location-page-components/MembershipSection';
import { Multisport } from '../components/authorable/location-page-components/Multisport';
import { PlayAndPractice } from '../components/authorable/location-page-components/PlayAndPractice';
import { Testimonials } from '../components/authorable/location-page-components/Testimonials';
import { AccordionItem } from '../components/ui/AccordionItem';
import { BodyCopy } from '../components/ui/BodyCopy';
import { BoxCardList } from '../components/ui/BoxCardList';
import { Coach } from '../components/ui/Coach';
import { Content } from '../components/ui/Content';
import { Cookies } from '../components/ui/Cookies';
import { CustomSelect } from '../components/ui/CustomSelect';
import { HealCodeWidget } from '../components/ui/HealCodeWidget';
import { HeroBanner } from '../components/ui/HeroBanner';
import { ImageItem } from '../components/ui/ImageItem';
import { LocationBookingBanner } from '../components/ui/LocationBookingBanner';
import { LocationsList } from '../components/ui/LocationsList';
import { MindBodyAppointments } from '../components/ui/MindBodyAppointments';
import { PopupCta } from '../components/ui/PopupCta';
import { RteStrip } from '../components/ui/RteStrip';
import { SearchForm } from '../components/ui/SearchForm';
import { SheetTable } from '../components/ui/SheetTable';
import { Slider } from '../components/ui/Slider';
import { StatsSection } from '../components/ui/StatsSection';
import { Testimonial } from '../components/ui/Testimonial';
import { VideoItem } from '../components/ui/VideoItem';
import { ZoomWrapper } from '../components/ui/ZoomWrapper';
import { BlogDetailBody } from '../components/ui/blog/BlogDetailBody';
import { BlogCard } from '../components/ui/cards/BlogCard';
import { BoxCard } from '../components/ui/cards/BoxCard';
import { CareerCard } from '../components/ui/cards/CareerCard';
import { PromoCards } from '../components/ui/cards/PromoCards';
import { PromosTwoColCard } from '../components/ui/cards/PromosTwoColCard';
import { UpcomingSessionCard } from '../components/ui/cards/UpcomingSessionCard';
import { BlogDetailBanner } from '../components/ui/custom-banners/BlogDetailBanner';
import { BlogDetailContentBanner } from '../components/ui/custom-banners/BlogDetailContentBanner';
import { JobDetailBanner } from '../components/ui/custom-banners/JobDetailBanner';
import { MainNavigation } from '../components/ui/footer/MainNavigation';
import { Contactus } from '../components/ui/forms/Contactus';
import { EventsInquiry } from '../components/ui/forms/EventsInquiry';
import { Form } from '../components/ui/forms/Form';
import { Leagues } from '../components/ui/forms/Leagues';
import { Lessons } from '../components/ui/forms/Lessons';
import { LocationMembership } from '../components/ui/forms/LocationMembership';
import { Membership } from '../components/ui/forms/Membership';
import { SubscribeForm } from '../components/ui/forms/SubscribeForm';
import { MainMenuNavigation } from '../components/ui/header/MainMenuNavigation';
import { ShowcaseNavigation } from '../components/ui/header/ShowcaseNavigation';
import { UtilityNavigation } from '../components/ui/header/UtilityNavigation';
import { JobDetail } from '../components/ui/job/JobDetail';
import { JobDetailBody } from '../components/ui/job/JobDetailBody';
import { Jobs } from '../components/ui/job/Jobs';
import { HeroBannerVideoModal } from '../components/ui/modals/HeroBannerVideoModal';
import { InfoModal } from '../components/ui/modals/InfoModal';
import { LocationHeroModal } from '../components/ui/modals/LocationHeroModal';
import { LocationPromoModal } from '../components/ui/modals/LocationPromoModal';
import { PromoModal } from '../components/ui/modals/PromoModal';
import { AutoImageSlider } from '../components/ui/slider-variants/AutoImageSlider';
import { GallerySlider } from '../components/ui/slider-variants/GallerySlider';
import { InfiniteSwipeSlider } from '../components/ui/slider-variants/InfiniteSwipeSlider';
import { PaginatedImageSlider } from '../components/ui/slider-variants/PaginatedImageSlider';
import { StripSlider } from '../components/ui/slider-variants/StripSlider';
import { componentMapperInstance } from '../utils/ComponentMapper';

// Component names as a type
export type ComponentTypes = 'BlogDetail' | 'BlogList' | 'BoxCards' | 'Coaches' | 'ContentRte' | 'ContentRteComponent' | 'EventsCard' | 'EventsList' | 'Faq' | 'FaqComponent' | 'Footer' | 'FormWrapper' | 'GamesBoxCard' | 'GamesBoxCardsList' | 'Header' | 'HeroBannerComponent' | 'HorizontalDivider' | 'Iconlist' | 'InlineBanner' | 'InlineBannerComponent' | 'Job' | 'JobList' | 'Layout' | 'LocationBookingBannerComponent' | 'Locations' | 'MembershipContent' | 'MembershipContentComponent' | 'PromoCardsList' | 'PromoTwocolCards' | 'QuickCardNavigation' | 'RteStripComponent' | 'Section' | 'SingleRteStrip' | 'SingleTestimonial' | 'SliderComponent' | 'StatsSectionComponent' | 'UpcomingSessionCardList' | 'VideoBanner' | 'VideoComponent' | 'ComingSoon' | 'ContactInformation' | 'CustomClubFitting' | 'DuckpinBowling' | 'DuckpinBowlingSection' | 'FreeParking' | 'GolfInstruction' | 'LocationDropdown' | 'LocationHeroBanner' | 'MakeItAParty' | 'MembershipSection' | 'Multisport' | 'PlayAndPractice' | 'Testimonials' | 'AccordionItem' | 'BodyCopy' | 'BoxCardList' | 'Coach' | 'Content' | 'Cookies' | 'CustomSelect' | 'HealCodeWidget' | 'HeroBanner' | 'ImageItem' | 'LocationBookingBanner' | 'LocationsList' | 'MindBodyAppointments' | 'PopupCta' | 'RteStrip' | 'SearchForm' | 'SheetTable' | 'Slider' | 'StatsSection' | 'Testimonial' | 'VideoItem' | 'ZoomWrapper' | 'BlogDetailBody' | 'BlogCard' | 'BoxCard' | 'CareerCard' | 'PromoCards' | 'PromosTwoColCard' | 'UpcomingSessionCard' | 'BlogDetailBanner' | 'BlogDetailContentBanner' | 'JobDetailBanner' | 'MainNavigation' | 'Contactus' | 'EventsInquiry' | 'Form' | 'Leagues' | 'Lessons' | 'LocationMembership' | 'Membership' | 'SubscribeForm' | 'MainMenuNavigation' | 'ShowcaseNavigation' | 'UtilityNavigation' | 'JobDetail' | 'JobDetailBody' | 'Jobs' | 'HeroBannerVideoModal' | 'InfoModal' | 'LocationHeroModal' | 'LocationPromoModal' | 'PromoModal' | 'AutoImageSlider' | 'GallerySlider' | 'InfiniteSwipeSlider' | 'PaginatedImageSlider' | 'StripSlider';

// Register all components with the ComponentMapper
componentMapperInstance.register('BlogDetail', BlogDetail);
componentMapperInstance.register('BlogList', BlogList);
componentMapperInstance.register('BoxCards', BoxCards);
componentMapperInstance.register('Coaches', Coaches);
componentMapperInstance.register('ContentRte', ContentRte);
componentMapperInstance.register('ContentRteComponent', ContentRteComponent);
componentMapperInstance.register('EventsCard', EventsCard);
componentMapperInstance.register('EventsList', EventsList);
componentMapperInstance.register('Faq', Faq);
componentMapperInstance.register('FaqComponent', FaqComponent);
componentMapperInstance.register('Footer', Footer);
componentMapperInstance.register('FormWrapper', FormWrapper);
componentMapperInstance.register('GamesBoxCard', GamesBoxCard);
componentMapperInstance.register('GamesBoxCardsList', GamesBoxCardsList);
componentMapperInstance.register('Header', Header);
componentMapperInstance.register('HeroBannerComponent', HeroBannerComponent);
componentMapperInstance.register('HorizontalDivider', HorizontalDivider);
componentMapperInstance.register('Iconlist', Iconlist);
componentMapperInstance.register('InlineBanner', InlineBanner);
componentMapperInstance.register('InlineBannerComponent', InlineBannerComponent);
componentMapperInstance.register('Job', Job);
componentMapperInstance.register('JobList', JobList);
componentMapperInstance.register('Layout', Layout);
componentMapperInstance.register('LocationBookingBannerComponent', LocationBookingBannerComponent);
componentMapperInstance.register('Locations', Locations);
componentMapperInstance.register('MembershipContent', MembershipContent);
componentMapperInstance.register('MembershipContentComponent', MembershipContentComponent);
componentMapperInstance.register('PromoCardsList', PromoCardsList);
componentMapperInstance.register('PromoTwocolCards', PromoTwocolCards);
componentMapperInstance.register('QuickCardNavigation', QuickCardNavigation);
componentMapperInstance.register('RteStripComponent', RteStripComponent);
componentMapperInstance.register('Section', Section);
componentMapperInstance.register('SingleRteStrip', SingleRteStrip);
componentMapperInstance.register('SingleTestimonial', SingleTestimonial);
componentMapperInstance.register('SliderComponent', SliderComponent);
componentMapperInstance.register('StatsSectionComponent', StatsSectionComponent);
componentMapperInstance.register('UpcomingSessionCardList', UpcomingSessionCardList);
componentMapperInstance.register('VideoBanner', VideoBanner);
componentMapperInstance.register('VideoComponent', VideoComponent);
componentMapperInstance.register('ComingSoon', ComingSoon);
componentMapperInstance.register('ContactInformation', ContactInformation);
componentMapperInstance.register('CustomClubFitting', CustomClubFitting);
componentMapperInstance.register('DuckpinBowling', DuckpinBowling);
componentMapperInstance.register('DuckpinBowlingSection', DuckpinBowlingSection);
componentMapperInstance.register('FreeParking', FreeParking);
componentMapperInstance.register('GolfInstruction', GolfInstruction);
componentMapperInstance.register('LocationDropdown', LocationDropdown);
componentMapperInstance.register('LocationHeroBanner', LocationHeroBanner);
componentMapperInstance.register('MakeItAParty', MakeItAParty);
componentMapperInstance.register('MembershipSection', MembershipSection);
componentMapperInstance.register('Multisport', Multisport);
componentMapperInstance.register('PlayAndPractice', PlayAndPractice);
componentMapperInstance.register('Testimonials', Testimonials);
componentMapperInstance.register('AccordionItem', AccordionItem);
componentMapperInstance.register('BodyCopy', BodyCopy);
componentMapperInstance.register('BoxCardList', BoxCardList);
componentMapperInstance.register('Coach', Coach);
componentMapperInstance.register('Content', Content);
componentMapperInstance.register('Cookies', Cookies);
componentMapperInstance.register('CustomSelect', CustomSelect);
componentMapperInstance.register('HealCodeWidget', HealCodeWidget);
componentMapperInstance.register('HeroBanner', HeroBanner);
componentMapperInstance.register('ImageItem', ImageItem);
componentMapperInstance.register('LocationBookingBanner', LocationBookingBanner);
componentMapperInstance.register('LocationsList', LocationsList);
componentMapperInstance.register('MindBodyAppointments', MindBodyAppointments);
componentMapperInstance.register('PopupCta', PopupCta);
componentMapperInstance.register('RteStrip', RteStrip);
componentMapperInstance.register('SearchForm', SearchForm);
componentMapperInstance.register('SheetTable', SheetTable);
componentMapperInstance.register('Slider', Slider);
componentMapperInstance.register('StatsSection', StatsSection);
componentMapperInstance.register('Testimonial', Testimonial);
componentMapperInstance.register('VideoItem', VideoItem);
componentMapperInstance.register('ZoomWrapper', ZoomWrapper);
componentMapperInstance.register('BlogDetailBody', BlogDetailBody);
componentMapperInstance.register('BlogCard', BlogCard);
componentMapperInstance.register('BoxCard', BoxCard);
componentMapperInstance.register('CareerCard', CareerCard);
componentMapperInstance.register('PromoCards', PromoCards);
componentMapperInstance.register('PromosTwoColCard', PromosTwoColCard);
componentMapperInstance.register('UpcomingSessionCard', UpcomingSessionCard);
componentMapperInstance.register('BlogDetailBanner', BlogDetailBanner);
componentMapperInstance.register('BlogDetailContentBanner', BlogDetailContentBanner);
componentMapperInstance.register('JobDetailBanner', JobDetailBanner);
componentMapperInstance.register('MainNavigation', MainNavigation);
componentMapperInstance.register('Contactus', Contactus);
componentMapperInstance.register('EventsInquiry', EventsInquiry);
componentMapperInstance.register('Form', Form);
componentMapperInstance.register('Leagues', Leagues);
componentMapperInstance.register('Lessons', Lessons);
componentMapperInstance.register('LocationMembership', LocationMembership);
componentMapperInstance.register('Membership', Membership);
componentMapperInstance.register('SubscribeForm', SubscribeForm);
componentMapperInstance.register('MainMenuNavigation', MainMenuNavigation);
componentMapperInstance.register('ShowcaseNavigation', ShowcaseNavigation);
componentMapperInstance.register('UtilityNavigation', UtilityNavigation);
componentMapperInstance.register('JobDetail', JobDetail);
componentMapperInstance.register('JobDetailBody', JobDetailBody);
componentMapperInstance.register('Jobs', Jobs);
componentMapperInstance.register('HeroBannerVideoModal', HeroBannerVideoModal);
componentMapperInstance.register('InfoModal', InfoModal);
componentMapperInstance.register('LocationHeroModal', LocationHeroModal);
componentMapperInstance.register('LocationPromoModal', LocationPromoModal);
componentMapperInstance.register('PromoModal', PromoModal);
componentMapperInstance.register('AutoImageSlider', AutoImageSlider);
componentMapperInstance.register('GallerySlider', GallerySlider);
componentMapperInstance.register('InfiniteSwipeSlider', InfiniteSwipeSlider);
componentMapperInstance.register('PaginatedImageSlider', PaginatedImageSlider);
componentMapperInstance.register('StripSlider', StripSlider);

// Export the componentMapperInstance for use in the application
export const componentMapper = componentMapperInstance;

// Export all components individually
export {
  BlogDetail,
  BlogList,
  BoxCards,
  Coaches,
  ContentRte,
  ContentRteComponent,
  EventsCard,
  EventsList,
  Faq,
  FaqComponent,
  Footer,
  FormWrapper,
  GamesBoxCard,
  GamesBoxCardsList,
  Header,
  HeroBannerComponent,
  HorizontalDivider,
  Iconlist,
  InlineBanner,
  InlineBannerComponent,
  Job,
  JobList,
  Layout,
  LocationBookingBannerComponent,
  Locations,
  MembershipContent,
  MembershipContentComponent,
  PromoCardsList,
  PromoTwocolCards,
  QuickCardNavigation,
  RteStripComponent,
  Section,
  SingleRteStrip,
  SingleTestimonial,
  SliderComponent,
  StatsSectionComponent,
  UpcomingSessionCardList,
  VideoBanner,
  VideoComponent,
  ComingSoon,
  ContactInformation,
  CustomClubFitting,
  DuckpinBowling,
  DuckpinBowlingSection,
  FreeParking,
  GolfInstruction,
  LocationDropdown,
  LocationHeroBanner,
  MakeItAParty,
  MembershipSection,
  Multisport,
  PlayAndPractice,
  Testimonials,
  AccordionItem,
  BodyCopy,
  BoxCardList,
  Coach,
  Content,
  Cookies,
  CustomSelect,
  HealCodeWidget,
  HeroBanner,
  ImageItem,
  LocationBookingBanner,
  LocationsList,
  MindBodyAppointments,
  PopupCta,
  RteStrip,
  SearchForm,
  SheetTable,
  Slider,
  StatsSection,
  Testimonial,
  VideoItem,
  ZoomWrapper,
  BlogDetailBody,
  BlogCard,
  BoxCard,
  CareerCard,
  PromoCards,
  PromosTwoColCard,
  UpcomingSessionCard,
  BlogDetailBanner,
  BlogDetailContentBanner,
  JobDetailBanner,
  MainNavigation,
  Contactus,
  EventsInquiry,
  Form,
  Leagues,
  Lessons,
  LocationMembership,
  Membership,
  SubscribeForm,
  MainMenuNavigation,
  ShowcaseNavigation,
  UtilityNavigation,
  JobDetail,
  JobDetailBody,
  Jobs,
  HeroBannerVideoModal,
  InfoModal,
  LocationHeroModal,
  LocationPromoModal,
  PromoModal,
  AutoImageSlider,
  GallerySlider,
  InfiniteSwipeSlider,
  PaginatedImageSlider,
  StripSlider,
};
